WebAPI/Controllers/FleetController.cs
//-----------------------------------------------------------------------
// <copyright file="SampleAppController.cs" company="Kenneth Larimer">
//  Copyright (c) 2017 All Rights Reserved
//  <author>Kenneth Larimer</author>
// </copyright>
//-----------------------------------------------------------------------

using API.Library.APIResources;
using API.Library.APIServices;
using API.Library.Common;
using API.Library.APIModels;
using SampleApp.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.Xml.Serialization;
using System.Xml;
using System.Net;
using API.Library.APIAttributes;
using API.Library.APIWrappers;
using API.Library.APIMappers;
using API.Library.Services;

namespace SampleApp.Controllers
{
    /// <summary>
    ///     Fleet controller for managing the Fleet_File
    /// </summary>
    [WebApiExceptionFilter]
    public class FleetController : Controller
    {
        /// <summary>
        ///     The data service
        /// </summary>
        private IDataService dataService;

        /// <summary>
        ///     The application settings service
        /// </summary>
        private IAppSettings appSettings;

        /// <summary>
        ///     The DateTime wrapper
        /// </summary>
        private IDateTime dateTimeWrapper;

        /// <summary>
        ///     The File IO service
        /// </summary>
        private IFileIOService fileIOService;

        /// <summary>
        ///     The Mapper
        /// </summary>
        private IHW_Mapper HW_Mapper;

        public FleetController()
        {
            this.dataService = null;
            appSettings = new ConfigAppSettings();
            fileIOService = new TextFileIOService(new ServerHostingEnvironmentService());
            dateTimeWrapper = new SystemDateTime();
            HW_Mapper = new HW_Mapper();

            this.dataService = new HW_DataService(appSettings, dateTimeWrapper, fileIOService, HW_Mapper);
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="SampleAppController" /> class.
        /// </summary>
        /// <param name="dataService">The injected data service</param>
        public FleetController(IDataService dataService)
        {
            this.dataService = dataService;
        }

        /// <summary>
        ///     Gets HW_Message value
        /// </summary>
        /// <returns>A HW_Message model containing HW_Message value</returns>
        [WebApiExceptionFilter(Type = typeof(IOException), Status = HttpStatusCode.ServiceUnavailable, Severity = SeverityCode.Error)]
        [WebApiExceptionFilter(Type = typeof(SettingsPropertyNotFoundException), Status = HttpStatusCode.ServiceUnavailable, Severity = SeverityCode.Error)]
        public HW_Message Get()
        {
            HW_Message ret = null;
            ret = this.dataService.GetHW_Message();
            return ret;
        }

        [WebApiExceptionFilter(Type = typeof(IOException), Status = HttpStatusCode.ServiceUnavailable, Severity = SeverityCode.Error)]
        [WebApiExceptionFilter(Type = typeof(SettingsPropertyNotFoundException), Status = HttpStatusCode.ServiceUnavailable, Severity = SeverityCode.Error)]
        public String Fleet_File_Load()
        {
            string ret = null;

            ret = this.dataService.GetFleet_File();
            return ret;
        }

        public static Fleet session_fleet = new Fleet();
        static bool session_fleet_file_invalid = false;

        public void Add_Vehicle(Vehicle veh)
        {
            if (session_fleet.get_NextID() > veh.id)
            {
                veh.id = session_fleet.get_NextID();
            }

            if (session_fleet.get_NextID() <= veh.id)
            {
                session_fleet.set_NextID(veh.id + 1);
            }

            session_fleet.FleetList.Add(veh);
        }

        public Fleet Load_Fleet_File()
        {
            session_fleet_file_invalid = false;
            String text = null;

            //if (dataService == null)
            //{
            //    var filePath = ConfigurationManager.AppSettings.Get(AppSettingsKeys.Fleet_File);
            //    var iFileIO = new TextFileIOService(new ServerHostingEnvironmentService());
            //    text = iFileIO.ReadFile(filePath);
            //}
            //else
                text = this.dataService.GetFleet_File();

            return Common.FromXml<Fleet>(text);
        }

        public void Save_Fleet_File()
        {
            if (session_fleet_file_invalid)
            {
                //if (dataService == null)
                //{
                //    var filePath = ConfigurationManager.AppSettings.Get(AppSettingsKeys.Fleet_File);

                //    var iFileIO = new TextFileIOService(new ServerHostingEnvironmentService());
                //    iFileIO.WriteFile(filePath, Common.ToXML(session_fleet));
                //}
                //else
                    this.dataService.PutFleet_File(Common.ToXML(session_fleet));
            }
        }

        // GET: Fleet
        public ActionResult Index()
        {
            //            /// <summary>
            //            ///     The Web Service
            //            /// </summary>
            //private readonly IHW_WebService WebService;

            ///// <summary>
            /////     The logger
            ///// </summary>
            //private readonly ILogger logger;

            //ViewBag.Title = "Fleet Page";
            //    this.WebService = WebService;
            //    this.logger = logger;
            ViewBag.Title = "Fleet Page";

            session_fleet = Load_Fleet_File();
            session_fleet.fix_NextID();

            var model = session_fleet; //  Create_Fleet_File();

            var vlist = Enum.GetValues(typeof(v_status)).Cast<v_status>().Select(v => new SelectListItem
            {
                Text = v.ToString(),
                Value = ((int)v).ToString()
                ,
                Selected = (v.ToString() == "stand-by")
            }).ToList();

            ViewBag.selectVehicleStatus = vlist;

            return View(model);
        }

        // GET: Fleet/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Fleet/Create
        public ActionResult Create()
        {
            Vehicle viewmodel = new Vehicle();

            var vlist = Enum.GetValues(typeof(v_type)).Cast<v_type>().Select(v => new SelectListItem
            {
                Text = v.ToString(),
                Value = ((int)v).ToString()
                ,
                Selected = (v.ToString() == "CAR")
            }).ToList();

            ViewBag.selectVehicleType = vlist;

            return View(viewmodel);
        }

        // POST: Fleet/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VMake,VModel,VYear,VVIN,VType,VStatus,VRegion,VLocation")] Vehicle model)
        {
            if (ModelState.IsValid && !string.IsNullOrEmpty(model.VVIN))
            {
                try
                {
                    // TODO: Add insert logic here
                    session_fleet = Load_Fleet_File();
                    session_fleet.fix_NextID();

                    model.id = session_fleet.get_NextID();

                    Add_Vehicle(new Vehicle(model.id, model.VMake, model.VModel, model.VYear, model.VType, model.VVIN,
                        model.VRegion, model.VLocation, model.VStatus));

                    session_fleet_file_invalid = true;

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }
        // GET: Fleet/Edit/5
        public ActionResult Transfer(int id)
        {
            Vehicle viewmodel = session_fleet.FleetList.Find(x => x.id == id);

            return View(viewmodel);
        }

        // POST: Fleet/Transfer/5
        [HttpPost]
        public ActionResult Transfer(int id, [Bind(Include = "VMake,VModel,VYear,VVIN,VType,VStatus,VRegion,VLocation")] Vehicle model)
        {
            try
            {
                // TODO: Add update logic here
                var veh = session_fleet.FleetList.Find(x => x.id == id);
                if (veh != null)
                {
                    if (veh.VStatus != model.VStatus || veh.VLocation != model.VLocation || veh.VRegion != model.VRegion)
                    {
                        session_fleet_file_invalid = true;
                        veh.VStatus = model.VStatus;
                        veh.VLocation = model.VLocation;
                        veh.VRegion = model.VRegion;
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Fleet/Edit/5
        public ActionResult Edit(int id)
        {
            Vehicle viewmodel = session_fleet.FleetList.Find(x => x.id == id);

            return View(viewmodel);
        }

        // POST: Fleet/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, [Bind(Include = "VMake,VModel,VYear,VVIN,VType,VStatus,VRegion,VLocation")] Vehicle model)
        {
            try
            {
                // TODO: Add update logic here
                var veh = session_fleet.FleetList.Find(x => x.id == id);
                if (veh != null)
                {
                    if (veh.VStatus != model.VStatus)
                    {
                        session_fleet_file_invalid = true;
                        //veh.VLocation = model.VLocation;

WebAPI/Views/Fleet/Create.cshtml
@model SampleApp.Models.Vehicle

@using (Html.BeginForm("Create", "Fleet", FormMethod.Post))
{
    <input type="hidden" name="V_Make" id="hdnV_Make" value="@Model.VMake" />
    <input type="hidden" name="V_Model" id="hdnV_Model" value="@Model.VModel" />
    <input type="hidden" name="V_Type" id="hdnV_Type" value="@Model.VType" />
    <input type="hidden" name="V_VIN" id="hdnV_VIN" value="@Model.VVIN" />
    <input type="hidden" name="V_Year" id="hdnV_Year" value="@Model.VYear" />
    <input type="hidden" name="V_Region" id="hdnV_Region" value="@Model.VRegion" />
    <input type="hidden" name="V_Location" id="hdnV_Location" value="@Model.VLocation" />
    <input type="hidden" name="V_Status" id="hdnV_Status" value="@Model.VStatus" />

    @Html.AntiForgeryToken()
    <div class="form-horizontal" style="width: 75%; margin-left: 12.5%;">
        <br />
        <h2>Create</h2>
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true)
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VMake, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.EditorFor(model => model.VMake)
                @Html.ValidationMessageFor(model => model.VMake)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VModel, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.EditorFor(model => model.VModel)
                @Html.ValidationMessageFor(model => model.VModel)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VVIN, new { @class = "control-label col-md-2", @style = " text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.EditorFor(model => model.VVIN, new { htmlAttributes = new { style = "width: 300px" }, })
                @Html.ValidationMessageFor(model => model.VVIN)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VYear, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.EditorFor(model => model.VYear)
                @Html.ValidationMessageFor(model => model.VYear)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VRegion, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.EditorFor(model => model.VRegion)
                @Html.ValidationMessageFor(model => model.VRegion)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VLocation, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.EditorFor(model => model.VLocation)
                @Html.ValidationMessageFor(model => model.VLocation)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VType, new { @class = "control-label col-md-2", @style = "text-align: left" })
            </dt>
            <dd style="padding-bottom:8px;">
                @{
                    var DisplayVehicleType = ViewBag.selectVehicleType as IEnumerable<SelectListItem>;
                    @Html.EnumDropDownListFor(m => m.VType, new { @class = "form-control" })
                }
                @Html.ValidationMessageFor(model => model.VType)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VStatus, new { @class = "control-label col-md-2", @style = "text-align: left" })
            </dt>
            <dd style="padding-bottom:8px;">
                @{
                    var DisplayVehicleStatus = ViewBag.selectVehicleStatus as IEnumerable<SelectListItem>;
                    @Html.EnumDropDownListFor(m => m.VStatus, new { @class = "form-control" })
                }
                @Html.ValidationMessageFor(model => model.VStatus)
            </dd>
        </dl>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-12">
                <input type="submit" value="Create" class="btn btn-success" style="margin-top:10px; color:white; height:35px; width:150px" />
            </div>
            @Html.ValidationMessage("CustomError")
            <br />
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}

WebAPI/Views/Fleet/Delete.cshtml
@model SampleApp.Models.Vehicle

@*@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_2Layout.cshtml";
}*@

<div style="width: 75%; margin-left: 12.5%;">
    <br />
    <h2>Vehicle</h2>
    <h3>Delete</h3>
    <table class="dl-horizontal">
        <tr>
            <td>
                @Html.LabelFor(model => model.id, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.id)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VMake, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VMake)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VModel, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VModel)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VVIN, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VVIN)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VYear, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VYear)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VType, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VType)
            <td />
        <tr />
        @*<tr>
            <td>
                @Html.LabelFor(model => model.ModifiedBy, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.ModifiedBy)
            <td />
        </tr>*@
        @*<tr class="form-group">
                <td class="col-md-offset-2 col-md-10">
                    <br />
                    <input type="submit" value="Delete" class="btn btn-success" style="margin-top:10px; color:white; height:35px; width:150px" />
                    <br />
                    <br />
                    @Html.ActionLink("Back to List", "Index")
                    <br />
                <td />
            <tr />*@
    </table>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div>
            <input type="submit" value="Delete" class="btn btn-success" style="margin-top:10px; color:white; height:35px; width:150px" />
            @*@Html.ActionLink("Back to List", "Index", new { usedatatable = @ViewBag.usedatatable })*@
            <br />
            <br />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    }
</div>

WebAPI/Views/Fleet/Edit.cshtml
@model SampleApp.Models.Vehicle

@*@{
        ViewBag.Title = "Delete";
        Layout = "~/Views/Shared/_2Layout.cshtml";
    }*@

<div style="width: 75%; margin-left: 12.5%;">
    <input type="hidden" name="V_Status" id="hdnV_Status" value="@Model.VStatus" />
    <input type="hidden" name="V_Region" id="hdnV_Region" value="@Model.VRegion" />
    <input type="hidden" name="V_Location" id="hdnV_Location" value="@Model.VLocation" />
    <br />
    <h2>Vehicle</h2>
    <h3>Transfer</h3>
    <table class="dl-horizontal">
        <tr>
            <td>
                @Html.LabelFor(model => model.id, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.id)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VMake, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VMake)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VModel, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VModel)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VVIN, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VVIN)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VYear, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VYear)
            <td />
        <tr />
        <tr>
            <td>
                @Html.LabelFor(model => model.VType, new { style = "margin-right:12px;" })
            <td />
            <td class="col-md-10">
                @Html.DisplayFor(model => model.VType)
            <td />
        <tr />
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VStatus, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.EnumDropDownListFor(model => model.VStatus, new { style = "width: 140px; text-align: left; ", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VStatus)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VRegion, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.DisplayFor(model => model.VRegion)
                @Html.ValidationMessageFor(model => model.VRegion)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt style="padding-bottom:8px;">
                @Html.LabelFor(model => model.VLocation, new { @class = "control-label col-md-2", @style = "text-align: left;" })
            </dt>
            <dd style="padding-top:8px;">
                @Html.DisplayFor(model => model.VLocation)
                @Html.ValidationMessageFor(model => model.VLocation)
            </dd>
        </dl>
        <div>
            <input type="submit" value="Change" class="btn btn-success" style="margin-top:10px; color:white; height:35px; width:150px" />
            <br />
            <br />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    }
</div>

@*<head>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<html>
<body>
    <div ng-app>
        <inpute type="text" id="txt1" ng-model="data" /> <br />
        The data is: {{ data }}
    </div>

</body>
</html>*@

WebAPI/Views/Fleet/Index.cshtml
@model SampleApp.Models.Fleet
@using API.Library.Common

@{
    var buildVersion = typeof(WebApiApplication).Assembly.GetName().Version;
    var version = buildVersion.ToString();

    DateTime julianRoot = DateTime.Parse("2000-01-01");
    var build = buildVersion.Build.ToString();
    var convertedDate = julianRoot.AddDays(buildVersion.Build)
                                .AddSeconds(2 * buildVersion.Revision); // + 3600); corrects for DST
    var relDate = string.Format("Release {0}", convertedDate.ToString("yyMMdd.HHmm"));
}

<div style="width: 75%; margin-left: 12.5%;">
    <h4>UniFirst Sample Fleet</h4>
    <br/>
    @Html.ActionLink("Create New", "Create")
    <br/>
    <br />
    <table class="table">
        <tr>
            @*<th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].id)
            </th>*@
            <th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VMake)
            </th>
            <th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VModel)
            </th>
           <th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VYear)
            </th>
            <th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VVIN)
            </th>
            <th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VRegion)
            </th>
            <th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VLocation)
            </th>
            @*<th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].TName)
            </th>*@
            <th>
                @*@Html.DisplayNameFor(dummy => @Model.FleetList[0].VType.ToDescription())*@
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VType)
            </th>
            <th>
                @Html.DisplayNameFor(dummy => @Model.FleetList[0].VStatus)
            </th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model.FleetList)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.VMake)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VModel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VVIN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VRegion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VLocation)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.VType.ToDescription())*@
                    @Html.DisplayFor(modelItem => item.VType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VStatus)
                </td>
                <td>
                    @if (item.VStatus.ToString() == "STANDBY")
                    {
                        @Html.ActionLink("Transfer", "Transfer", new { id = item.id })
                    }
                    else
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.id })
                    }
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }
    </table>
</div>
<div style="text-align: center;">@relDate &bull; Version @version</div>

WebAPI/Views/Fleet/Transfer.cshtml
<head>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<html>
<body>
    <div ng-app>
        <inpute type="text" id="txt1" ng-model="data" /> <br />
        The data is: {{ data }}
    </div>

</body>
</html>